import time
import logging
from typing import Callable, Any, Dict
from .config import settings

logger = logging.getLogger(__name__)

class CircuitBreaker:
    def __init__(self, failure_threshold: int = 3, recovery_timeout: int = 60):
        self.failure_threshold = failure_threshold
        self.recovery_timeout = recovery_timeout
        self.failure_count = 0
        self.last_failure_time = 0
        self.state = "CLOSED"  # CLOSED, OPEN, HALF_OPEN

    def record_failure(self):
        self.failure_count += 1
        self.last_failure_time = time.time()
        if self.failure_count >= self.failure_threshold:
            self.state = "OPEN"
            logger.warning("Circuit breaker tripped! State changed to OPEN.")

    def record_success(self):
        self.failure_count = 0
        self.state = "CLOSED"

    def is_allowed(self) -> bool:
        if self.state == "CLOSED":
            return True

        if self.state == "OPEN":
            if time.time() - self.last_failure_time > self.recovery_timeout:
                self.state = "HALF_OPEN"
                logger.info("Circuit breaker recovery timeout reached. State changed to HALF_OPEN.")
                return True
            return False

        if self.state == "HALF_OPEN":
            return True

        return True

ai_circuit_breaker = CircuitBreaker()
twilio_circuit_breaker = CircuitBreaker()

async def execute_with_circuit_breaker(breaker: CircuitBreaker, primary_func: Callable, fallback_func: Callable, *args, **kwargs) -> Any:
    if breaker.is_allowed():
        try:
            result = await primary_func(*args, **kwargs)
            breaker.record_success()
            return result
        except Exception as e:
            logger.error(f"Primary function failed: {e}")
            breaker.record_failure()
            logger.info("Falling back to local alternative.")
            return await fallback_func(*args, **kwargs)
    else:
        logger.warning("Circuit breaker is OPEN. Executing fallback immediately.")
        return await fallback_func(*args, **kwargs)

def get_local_llm_fallback() -> Dict:
    # A generic mock response or interaction with a local Ollama model
    return {
        "incident_title": "Local Fallback Reroute Plan",
        "situation_summary": "Generated by local fallback model due to API outage.",
        "maintenance_task": "Inspect standard protocols.",
        "operations_task": "Ensure manual tracking.",
        "station_manager_task": "Issue passenger advisories manually.",
        "passenger_sms": "We are experiencing delays. Please listen to announcements.",
        "confidence_score": 50,
        "reasoning_steps": ["API failed.", "Using local fallback.", "Generating generic safe tasks."],
        "passenger_impact": "Unknown",
        "prediction": "Unknown"
    }
